<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>書記 Online</title>
    <meta name="referrer" content="always">
    <meta name="renderer" content="webkit">
    <link href="/img/favicon.png" rel="shortcut icon" type="image/x-icon">
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/app.css" rel="stylesheet">
    <link href="/css/material-design-iconic-font.min.css" rel="stylesheet">
    <link href="/handsontable/handsontable.full.css" rel="stylesheet" media="screen">
    <script src="/js/jquery.min.js"></script>
    <script src="/handsontable/handsontable.full.js"></script>
    <script src="/js/app.js"></script>
</head>
<body>
    <!-- HelloScreen -->
    <div class="hello-screen" id="helloScreen">
        <div class="big-title-text">
            <h2>書記 Online</h2>
        </div>
        <form class="hello-form" id="helloForm">
            <p class="input-hint">填入你的名字，成为一名名副其实的图书登记员吧！</p>
            <input type="text" id="yourName" class="form-control" placeholder="Your Name. 填入你的真实名字." required autocomplete="off" autofocus />
            <button class="hello-form-submit">好的</button>
        </form>
    </div>
    <!-- CategoryList -->
    <div class="category-list-wrap" id="categoryListLayer" style="display: none">
         <div class="category-list" id="categoryList">
             <div class="list-head">
                 <span class="list-title">图书类目列表</span>
                 <span class="close-btn zmdi zmdi-close" onclick="app.categoryList.hide();"></span>
             </div>
             <div class="list-body">
                 <div class="list-toolbar">
                     <span onclick="app.categoryList.createCategory();">新建类目</span>
                 </div>
                 <div class="list-loading" id="categoryListLoading">正在加载中...</div>
                 <div class="list-content" id="categoryListContent"></div>
             </div>
        </div>
    </div>
    <!-- WorkArea -->
    <div class="work-area" id="workArea" style="display: none">
        <div class="work-table" id="workTable"></div>
        <div class="floaters">
            <div class="floater-block block-hide">
                <span>书记 Online</span>
            </div>
        </div>
    </div>
</body>
</html>