<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>書記 Online</title>
    <meta name="referrer" content="always">
    <meta name="renderer" content="webkit">
    <link href="/img/ingteresting.png" rel="shortcut icon" type="image/x-icon">
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/app.css" rel="stylesheet">
    <link href="/css/material-design-iconic-font.min.css" rel="stylesheet">
    <script src="/js/jquery.min.js"></script>
    <script src="/js/app.js"></script>
    <!--[if lt IE 9]>你正在使用的浏览器版本过低，请<a href="/upgrade-browser.html"><strong>升级你的浏览器</strong></a>，获得最佳的浏览体验！<![endif]-->
</head>
<body>
    <!-- PageLoaderLayer -->
    <div class="page-loader-layer" id="pageLoaderLayer">
        <div class="page-loader-img">
            <img src="/img/ingteresting.png" class="loader-img">
        </div>
        <div class="loading-text"></div>
    </div>
    
    <!-- mainScreen -->
    <div class="main-wrap" style="display: none">
        <div class="main">
            
            <div class="main-head">
                <div class="big-title">
                    <span class="project-name">書記</span><span class="version-info">Online</span>
                </div>
                <div class="head-actions">
                    <span class="user-name"><i class="zmdi zmdi-account"></i><span class="action-text"></span></span>
                </div>
            </div>
            
            <form class="main-login" onsubmit="return false;">
                <p class="input-hint">填入你的名字，成为一名名副其实的图书登记员吧！</p>
                <input type="text" id="yourName" class="form-control" placeholder="Your Name ? 填入你的真实名字." autofocus autocomplete="off" />
                <button class="login-submit">好的</button>
            </form>
            
            <div class="main-category-list-wrap"></div>
        </div>
    </div>
    <!-- WorkArea -->
    <div class="work-area" id="workArea" style="display: none">
        <div class="work-table" id="workTable"></div>
        <div class="floaters">
            <div class="work-actions">
                <span class="action-item" onclick="app.work.saveCurrent()"><i class="zmdi zmdi-save"></i> 保存</span>
                <span class="action-item" onclick="app.work.exitWork()"><i class="zmdi zmdi-arrow-back"></i> 离开</span>
            </div>
        </div>
    </div>
</body>
</html>